[env:lilygo-t5-47-plus]
platform = espressif32
board = lilygo-t5-47-plus
framework = arduino
monitor_speed = 115200

lib_deps =
  Xinyuan-LilyGO/LilyGo_EPD47@^1.0.1
  bblanchon/ArduinoJson@^7

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=1

; If your PlatformIO doesn't know the board, switch to:
; board = esp32-s3-devkitc-1
; board_build.psram = opi
